# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62f249e04b2caa7b90db0ac2e41e75a788f64bc6c8151a2cff5ecf625cf62b9bd82dab8faa5eb5e3689154d2f4b64dac8f554662bc7edc74ba76a773924f6e02

test:
  secret_key_base: 4d5fdaa91ca77bab08250a01b376103832f2231f3557b794d329d595a58dddbc5c02ccb63eae62dfb53b1b64990d81832d81ed8f0938e0b16a7d1feb9240bfd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  s3_secret_access: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  s3_region: <%= ENV["AWS_REGION"] %>
  s3_bucket: <%= ENV["AWS_BUCKET"] %>
